Languages/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^languages/', include('apps.languages.urls', namespace='languages')),
    url(r'^', include('apps.loginreg.urls', namespace='users')),
]

apps/languages/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^new$', views.new, name="new"),
    url(r'^create$', views.create, name="create"),
    url(r'^show/(?P<id>\d+)$', views.show, name="show"),
    url(r'^edit/(?P<id>\d+)$', views.edit, name="edit"),
    url(r'^update/(?P<id>\d+)$', views.update, name="update"),
    url(r'^destroy/(?P<id>\d+)$', views.delete, name="destroy"),
    url(r'^like/(?P<id>\d+)$', views.like, name="like"),
]

apps/loginreg/urls.py
from django.conf.urls import url
# from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.login, name='login'),
    url(r'^register$', views.register, name='register'),
    url(r'^logout$', views.logout, name='logout')
]

apps/languages/models.py
from __future__ import unicode_literals
from ..loginreg.models import User
from django.db import models

# Create your models here.
class LanguageManager(models.Manager):
    def validate_language(self, **kwargs):
        message_list = []
        if len(kwargs['name']) < 2:
            message_list.append("Language name must be at least 2 characters")
            return (False, message_list)
        else:
            message_list.append("Language saved successfully")
            self.create(name=kwargs['name'])
            return (True, message_list)

class Language(models.Model):
    name = models.CharField(max_length=16)
    users = models.ManyToManyField(User)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = LanguageManager()

apps/loginreg/models.py
from __future__ import unicode_literals
import bcrypt, re
from django.contrib import messages
from django.db import models

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')

class UserManager(models.Manager):
    def login(self, **kwargs):
        if kwargs is not None:
            errors = {}
            if len(kwargs['password']) == 0:
                errors['password'] = "Please Enter a Password"
            if len(kwargs['email']) == 0:
                errors['email'] = "Please Enter an Email"
            if len(errors) != 0:
                return (False, errors)
            else:
                user = self.filter(email=kwargs['email'])
                if not user:
                    errors['user'] = "Email/Password Combination Not Found"
                    return (False, errors)
                else:
                    if bcrypt.checkpw(kwargs['password'].encode('utf-8'), user[0].password.encode('utf-8')):
                        return (True, user[0])
                    else:
                        errors['user'] = "Email/Password Combination Not Found"
                        return (False, errors)

    def register(self, **kwargs):
        if kwargs is not None:
            errors = {}
            if len(kwargs['first_name']) < 2:
                errors['first_name'] = "First Name must be at least 2 characters"
            if len(kwargs['last_name']) < 2:
                errors['last_name'] = "Last Name must be at least 2 characters"
            if len(kwargs['email']) == 0:
                errors['email'] = "Email is required"
            elif not EMAIL_REGEX.match(kwargs['email']):
                errors['email'] = "Please enter a valid email"
            if len(kwargs['password']) < 8:
                errors['password'] = "Password must be at least 8 characters"
            if kwargs['password'] != kwargs['c_password']:
                errors['c_password'] = "Passwords must match"
            if len(errors) is not 0:
                return (False, errors)
            else:
                hashed = bcrypt.hashpw(kwargs['password'].encode('utf-8'), bcrypt.gensalt())
                user = self.create(first_name=kwargs['first_name'], last_name=kwargs['last_name'], email=kwargs['email'], password=hashed)
                user.save()
                return (True, user)
        else:
            messages.add_message(request, messages.INFO, "Please Try Registration Again")
            return

# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    password = models.CharField(max_length=100)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    objects = UserManager()

apps/languages/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import Language
from ..loginreg.models import User
# Create your views here.
def index (request):
    languages = Language.objects.all()
    return render(request, 'languages/index.html', {'languages' : languages})

def new (request):
    return render(request, 'languages/new.html')

def create (request):
    if request.method == 'POST':
        result = Language.objects.validate_language(name=request.POST['name'])
        print result
        if result[0]:
            return redirect(reverse('languages:index'))
        else:
            for message in result[1]:
                messages.error(request, message)
            return redirect(reverse('languages:new'))
    else:
        return redirect(reverse('languages:index'))

def show (request, id):
    language = Language.objects.get(id=id)
    liking_users = language.users.all()
    print language
    print liking_users
    return render(request, 'languages/show.html', {'language':language, 'liking_users': liking_users})

def edit (request, id):
    language = Language.objects.get(id=id)
    print language
    return render(request, 'languages/edit.html', {'language':language})

def update (request, id):
    if request.method == 'POST':
        if len(request.POST['name'])<2:
            messages.error(request, 'Name must be at least 2 characters')
            return redirect(reverse('edit', kwargs={'id':id}))
        else:
            language = Language.objects.get(id=id)
            language.name = request.POST['name']
            print language.name
            language.save()
            return redirect(reverse('languages:show', kwargs={'id':id}))
    else:
        return redirect(reverse('languages:edit', kwargs={'id':id})) #Gosh, I want to send them back to the specific language's edit page!

def delete (request, id):
    pass

def like (request, id):
    user = User.objects.get(id=request.session['user_id'])
    lang = Language.objects.get(id=id)
    lang.users.add(user)
    lang.save()
    return redirect(reverse('languages:show', kwargs={'id':id}))

apps/loginreg/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib import messages
from django.core.urlresolvers import reverse

# Create your views here.
def index(request):
    return render(request, 'loginreg/index.html')

def logout(request):
    request.session.clear()
    return redirect(reverse('users:index'))

def login(request):
    if request.method == "POST":
        result = User.objects.login(email=request.POST['email'], password=request.POST['password'])
        if result[0]:
            request.session['user_id'] = result[1].id
            return redirect(reverse('languages:index'))
        else:
            for error in result[1]:
                messages.add_message(request, messages.INFO, result[1][error])
            return redirect(reverse('users:index'))
    else:
        messages.add_message(request, messages.INFO, 'Please Try Again')
        return redirect(reverse('users:index'))

def register(request):
    if request.method == "POST":
        result = User.objects.register(first_name=request.POST['first_name'], last_name=request.POST['last_name'], email=request.POST['email'], password=request.POST['password'], c_password=request.POST['c_password'])
        if result[0]:
            request.session['user_id'] = result[1].id
            return redirect(reverse('languages:index'))
        else:
            for error in result[1]:
                messages.add_message(request, messages.INFO, result[1][error])
            return redirect(reverse('users:index'))
    else:
        messages.add_message(request, messages.INFO, 'Please Try Again')
        return redirect(reverse('users:index'))

def success(request):
    return render(request, 'loginreg/success.html')

apps/languages/templates/languages/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Edit Page</title>
</head>
<body>
  <h1>Let's edit {{language.name}}</h1>
  {% if messages %}
    {% for message in messages %}
      <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{message}}</p>
    {% endfor %}
  {% endif %}
  <form action="{% url 'languages:update' id=language.id %}" method="post">
    {% csrf_token %}
    <input type="text" name="name" value="{{language.name}}">
    <input type="submit" value="Update">
  </form>
</body>
</html>

apps/languages/templates/languages/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Languages Index</title>
</head>
<body>
  <h1>Languages Page!</h1>
  <a href="{% url 'users:logout' %}">Logout</a>
  <a href="{% url 'languages:new' %}">Add a Language</a>
  <table>
    <thead>
      <th>Name</th>
      <th>Action</th>
    </thead>
    <tbody>
      {% for language in languages %}
      <tr>
        <td><a href="{% url 'languages:show' id=language.id %}">{{language.name}}</a></td>
        <td><a href="{% url 'languages:edit' id=language.id %}">Edit</a> | <a href="{% url 'languages:destroy' id=language.id %}">Delete</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</body>
</html>

apps/languages/templates/languages/new.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>New Language</title>
</head>
<body>
  <h1>Create a Language</h1>
  <form action="{% url 'languages:create' %}" method="post">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Language Name...">
    <input type="submit" value="Create">
  </form>
</body>
</html>

apps/languages/templates/languages/show.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Show Page</title>
</head>
<body>
  <h1>{{language.name}} Show Page</h1>
  <a href="{% url 'languages:index' %}">Home</a>
  <table>
    <th>Users Who Like This</th>
    {% for user in liking_users %}
    <tr>
      <td>{{user.first_name}} {{user.last_name}}</td>
    </tr>
    {% endfor %}
  </table>
  <a href="{% url 'languages:like' id=language.id %}"><button>Like</button></a>
</body>
</html>

apps/loginreg/templates/loginreg/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Login/Reg</title>
</head>
<body>
  {% if messages %}
    {% for message in messages %}
    <p>{{message}}</p>
    {% endfor %}
  {% endif %}
  <h1>Registration</h1>
  <form action="{% url 'users:register' %}" method="post">
    {% csrf_token %}
    <p>First Name: <input type="text" name="first_name"></p>
    <p>Last Name: <input type="text" name="last_name"></p>
    <p>Email: <input type="text" name="email"></p>
    <p>Password: <input type="password" name="password"></p>
    <p>Confirm Password: <input type="password" name="c_password"></p>
    <input type="submit" value="Register">
  </form>
  <h1>Login</h1>
  <form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <p>Email: <input type="text" name="email"></p>
    <p>Password: <input type="password" name="password"></p>
    <input type="submit" value="Login">
  </form>
</body>
</html>